/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xUcTA1TSh7A
 */
import { Button } from "@/components/ui/button";
import {
  DialogTrigger,
  DialogTitle,
  DialogHeader,
  DialogFooter,
  DialogContent,
  Dialog,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import UploadButton from "@/app/recipes/upload-button";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus } from "@fortawesome/free-solid-svg-icons/faPlus";

export function AddRecipeAlert() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="ghost" className="w-full justify-start">
          <div className="flex flex-row">
            <FontAwesomeIcon icon={faPlus} className="mr-2 h-4 w-4" />
            Add New Recipe
          </div>
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Add Recipe</DialogTitle>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="image">Image</Label>
              <UploadButton />
              {/* 
              <Input id="image" type="file" /> */}
            </div>
            <div className="grid gap-2">
              <Label htmlFor="title">Title</Label>
              <Input id="title" placeholder="Enter recipe title" type="text" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="ingredients">Ingredients</Label>
              <div className="grid gap-2">
                <div className="grid grid-cols-2 gap-4">
                  <Input id="ingredient-1" placeholder="Ingredient" />
                  <Input id="quantity-1" placeholder="Quantity" />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <Input id="ingredient-2" placeholder="Ingredient" />
                  <Input id="quantity-2" placeholder="Quantity" />
                </div>
              </div>
              <Button>Add Ingredient</Button>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="directions">Directions</Label>
              <div className="grid gap-2">
                <Textarea id="directions-1" placeholder="Directions" />
                <Textarea id="directions-2" placeholder="Directions" />
              </div>
              <Button>Add Directions</Button>
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button type="submit">Add Recipe</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
